package main

import (
	"testing"
)

func TestTransform(t *testing.T) {
	testCases := []struct {
		name     string
		input    string
		expected string
	}{
		{
			input:    "TAKE 2 TABLETS (10 MG TOTAL) BY MOUTH 2 (TWO) TIMES A DAY WITH MEALS",
			expected: "PRENDRE 2 COMPRIMÉS (10 MG) PAR LA BOUCHE 2 FOIS PAR JOUR AVEC LES REPAS",
		},
		{
			input:    "TAKE 1 TABLET (250 MG TOTAL) BY MOUTH 3 (THREE) TIMES A DAY MAX DAILY AMOUNT: 750 MG",
			expected: "PRENDRE 1 COMPRIMÉ (250 MG) PAR LA BOUCHE 3 FOIS PAR JOUR (DOSE MAX PAR JOUR: 750 MG)",
		}, {
			input:    "TAKE 5-10 MLS BY MOUTH EVERY 4 (FOUR) TO 6 (SIX) HOURS AS NEEDED (COUGH) FOR UP TO 30 DAYS",
			expected: "PRENDRE 5-10 ML PAR LA BOUCHE AUX 4 À 6 HEURES AU BESOIN (TOUX) POUR 30 JOURS",
		},
		{
			input:    "TAKE 3 ML (1.25 MG TOTAL) BY NEBULIZATION EVERY 4 (FOUR) HOURS AS NEEDED FOR WHEEZING (COUGH)",
			expected: "PRENDRE 3 ML (1,25 MG) EN NÉBULISATION AUX 4 HEURES AU BESOIN SI RESPIRATION SIFFLANTE (TOUX)",
		},
		{
			input:    "TAKE THREE TABLET(S) (30 MG TOTAL) BY MOUTH AT BEDTIME",
			expected: "PRENDRE TROIS COMPRIMÉ(S) (30 MG) PAR LA BOUCHE AU COUCHER",
		},
		{
			input:    "TAKE 0.6 MLS BY MOUTH 2 (TWO) TIMES DAILY FOR 30 DAYS",
			expected: "PRENDRE 0,6 ML PAR LA BOUCHE 2 FOIS PAR JOUR POUR 30 JOURS",
		}, {
			input:    "TAKE 5-10 MLS BY MOUTH EVERY 4 (FOUR) TO 6 (SIX) HOURS AS NEEDED (COUGH) FOR UP TO 30 DAYS",
			expected: "PRENDRE 5-10 ML PAR LA BOUCHE AUX 4 À 6 HEURES AU BESOIN (TOUX) POUR 30 JOURS",
		},
		{
			input:    "INJECT 50 UNITS UNDER THE SKIN NIGHTLY",
			expected: "INJECTER 50 UNITÉS SOUS LA PEAU 1 FOIS PAR JOUR AU COUCHER",
		},
		{
			input:    "INHALE 2 PUFFS EVERY 4 HOURS AS NEEDED FOR WHEEZING",
			expected: "INHALER 2 BOUFFÉES AUX 4 HEURES AU BESOIN SI RESPIRATION SIFFLANTE",
		},
		{
			input:    "7.5 ML TWICE DAILY X 10 DAYS",
			expected: "7,5 ML 2 FOIS PAR JOUR X 10 JOURS",
		},
		{
			input:    "ONE TAB ORALLY EVERY DAY",
			expected: "UN COMPRIMÉ PAR LA BOUCHE 1 FOIS PAR JOUR",
		},
		{
			input:    "TAKE 650 MG BY MOUTH EVERY 6 (SIX) HOURS AS NEEDED FOR MILD PAIN (1-3) OR FEVER",
			expected: "PRENDRE 650 MG PAR LA BOUCHE AUX 6 HEURES AU BESOIN POUR DOULEUR LÉGÈRE OU FIÈVRE",
		},
		{
			input:    "PLACE 1 PATCH ONTO THE SKIN EVERY 7 DAYS",
			expected: "APPLIQUER 1 TIMBRE SUR LA PEAU À TOUS LES 7 JOURS",
		},
		{
			input:    "TAKE 1 TABLET BY MOUTH EVERY 6 (SIX) HOURS AS NEEDED FOR FEVER",
			expected: "PRENDRE 1 COMPRIMÉ PAR LA BOUCHE AUX 6 HEURES AU BESOIN POUR LA FIÈVRE",
		},
		{
			input:    "TAKE 1 CAPSULE (40 MG TOTAL) BY MOUTH EVERY 12 (TWELVE) HOURS FOR 30 DAYS",
			expected: "PRENDRE 1 CAPSULE (40 MG) PAR LA BOUCHE AUX 12 HEURES POUR 30 JOURS",
		},
		{
			input:    "TAKE 2.5 MG BY NEBULIZATION 3 (THREE) TIMES DAILY",
			expected: "PRENDRE 2,5 MG EN NÉBULISATION 3 FOIS PAR JOUR",
		},
		{
			input:    "TAKE 1 CAPSULE(300 MG) BY MOUTH THREE TIMES DAILY MAX DAILY AMOUNT: 900 MG",
			expected: "PRENDRE 1 CAPSULE(300 MG) PAR LA BOUCHE 3 FOIS PAR JOUR (DOSE MAX PAR JOUR: 900 MG)",
		},
		{
			input:    "TAKE 5 ML (125 MG TOTAL) BY MOUTH 2 (TWO) TIMES A DAY FOR 10 DAYS MAX DAILY AMOUNT: 250 MG",
			expected: "PRENDRE 5 ML (125 MG) PAR LA BOUCHE 2 FOIS PAR JOUR POUR 10 JOURS (DOSE MAX PAR JOUR: 250 MG)",
		},
		{
			input:    "APPLY TOPICALLY ONCE AS NEEDED",
			expected: "APPLIQUER LOCALEMENT 1 FOIS AU BESOIN",
		},
		{
			input:    "INSTILL 1 DROP INTO THE LEFT EYE DAILY",
			expected: "INSTILLER 1 GOUTTE DANS L'OEIL GAUCHE 1 FOIS PAR JOUR",
		},
		{
			input:    "TAKE 1 TABLET (500 MG TOTAL) BY MOUTH 2 (TWO) TIMES A DAY FOR 6 DOSES",
			expected: "PRENDRE 1 COMPRIMÉ (500 MG) PAR LA BOUCHE 2 FOIS PAR JOUR POUR 6 DOSES",
		},
		{
			input:    "TAKE 1 TABLET BY MOUTH TWICE A DAY AS NEEDED FOR PAIN",
			expected: "PRENDRE 1 COMPRIMÉ PAR LA BOUCHE 2 FOIS PAR JOUR AU BESOIN POUR DOULEUR",
		},
		{
			input:    "TAKE 25 MG BY MOUTH EVERY EVENING",
			expected: "PRENDRE 25 MG PAR LA BOUCHE CHAQUE SOIR",
		},
		{
			input:    "TAKE 4 MG BY MOUTH ONCE A DAY",
			expected: "PRENDRE 4 MG PAR LA BOUCHE 1 FOIS PAR JOUR",
		},
		{
			input:    "APPLY TO SKIN 2 TIMES DAILY AS NEEDED FOR ITCHING",
			expected: "APPLIQUER SUR LA PEAU 2 FOIS PAR JOUR AU BESOIN POUR PRURIT",
		},
		{
			input:    "PLACE ONE DROP(S) TO TWO DROP(S) IN AFFECTED EYE(S) EVERY 4 HOURS FOR 5 DAYS",
			expected: "APPLIQUER UNE GOUTTE(S) À DEUX GOUTTE(S) DANS LES YEUX AFFECTÉS AUX 4 HEURES POUR 5 JOURS",
		},
		{
			input:    "INHALE ONE PUFF(S) BY MOUTH ONCE A DAY",
			expected: "INHALER UNE BOUFFÉE(S) PAR LA BOUCHE 1 FOIS PAR JOUR",
		},
		{
			input:    "TAKE 100 MG BY MOUTH THREE TIMES A DAY",
			expected: "PRENDRE 100 MG PAR LA BOUCHE 3 FOIS PAR JOUR",
		},
		{
			input:    "APPLY TO AFFECTED AREA 3 TIMES DAILY",
			expected: "APPLIQUER SUR LA ZONE AFFECTÉE 3 FOIS PAR JOUR",
		},
		{
			input:    "TAKE 40 MG BY MOUTH EVERY OTHER DAY",
			expected: "PRENDRE 40 MG PAR LA BOUCHE AUX 2 JOURS",
		},
		{
			input:    "TAKE 1 CAPSULE WEEKLY",
			expected: "PRENDRE 1 CAPSULE 1 FOIS PAR SEMAINE",
		},
		{
			input:    "TAKE ONE TABLET BY MOUTH ONE TIME A DAY",
			expected: "PRENDRE UN COMPRIMÉ PAR LA BOUCHE 1 FOIS PAR JOUR",
		},
		{
			input:    "APPLY 1 DROP TO EYE NIGHTLY",
			expected: "APPLIQUER 1 GOUTTE DANS L'OEIL 1 FOIS PAR JOUR AU COUCHER",
		},
		{
			input:    "INJECT 0.3 ML (0.15 MG TOTAL) INTRAMUSCULARLY ONCE FOR 1 DOSE",
			expected: "INJECTER 0,3 ML (0,15 MG) PAR VOIE INTRAMUSCULAIRE POUR 1 DOSE",
		},
		{
			input:    "TAKE 600 MG BY MOUTH 4 (FOUR) TIMES A DAY",
			expected: "PRENDRE 600 MG PAR LA BOUCHE 4 FOIS PAR JOUR",
		},
		{
			input:    "PRENDRE 1 COMPRIMÉ (1,000 MG TOTAL) PAR LA BOUCHE 1 FOIS PAR JOUR AU COUCHER",
			expected: "PRENDRE 1 COMPRIMÉ (1000 MG) PAR LA BOUCHE 1 FOIS PAR JOUR AU COUCHER",
		},
		{
			input:    "TAKE 10 ML (1 G TOTAL) BY MOUTH 4 (FOUR) TIMES A DAY (BEFORE MEALS AND NIGHTLY)",
			expected: "PRENDRE 10 ML (1 G) PAR LA BOUCHE 4 FOIS PAR JOUR (AVANT LES REPAS ET AU COUCHER)",
		},
		{
			input:    "PLACE 1 APPLICATOR VAGINALLY NIGHTLY",
			expected: "INSÉRER 1 APPLICATEUR DANS LE VAGIN 1 FOIS PAR JOUR AU COUCHER",
		},
		{
			input:    "PLACE RECTALLY 3 (THREE) TIMES DAILY",
			expected: "INSÉRER DANS LE RECTUM 3 FOIS PAR JOUR",
		},
		{
			input:    "TAKE 1 TABLET BY MOUTH NIGHTLY AS NEEDED MAX DAILY AMOUNT: 0.5 MG",
			expected: "PRENDRE 1 COMPRIMÉ PAR LA BOUCHE 1 FOIS PAR JOUR AU COUCHER AU BESOIN (DOSE MAX PAR JOUR: 0,5 MG)",
		},
		{
			input:    "TAKE 1 CAPSULE (300 MG TOTAL) BY MOUTH 4 (FOUR) TIMES A DAY MAX DAILY AMOUNT: 1,200 MG",
			expected: "PRENDRE 1 CAPSULE (300 MG) PAR LA BOUCHE 4 FOIS PAR JOUR (DOSE MAX PAR JOUR: 1200 MG)",
		},
		{
			input:    "TAKE 1 TABLET BY MOUTH EVERY NIGHT AT BEDTIME",
			expected: "PRENDRE 1 COMPRIMÉ PAR LA BOUCHE CHAQUE SOIR AU COUCHER",
		},
		{
			input:    "SPRAY TWO SPRAY(S) IN BOTH NOSTRILS ONCE A DAY",
			expected: "VAPORISER DEUX VAPORISATION(S) DANS CHAQUE NARINE 1 FOIS PAR JOUR",
		},
		{
			input:    "INJECT 1 ML (5,000 UNITS TOTAL) UNDER THE SKIN EVERY 8 (EIGHT) HOURS",
			expected: "INJECTER 1 ML (5000 UNITÉS TOTAL) SOUS LA PEAU AUX 8 HEURES",
		},
		{
			input:    "TAKE 50,000 UNITS BY MOUTH EVERY 14 (FOURTEEN) DAYS",
			expected: "PRENDRE 50000 UNITÉS PAR LA BOUCHE EVERY 14 (FOURTEEN) DAYS",
		},
		{
			input:    "APPLY BID TO THE RASH",
			expected: "APPLIQUER 2 FOIS PAR JOUR SUR LES ROUGEURS",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			actual := Transform(tc.input)

			if actual != tc.expected {
				t.Errorf("\nI: %v\nE: %v\nA: %v", tc.input, tc.expected, actual)
				return
			}
		})
	}
}
